# Generated by Django 4.0 on 2021-12-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryNumber', models.IntegerField(unique=True)),
                ('file_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('check_field', models.BooleanField(default=False)),
            ],
        ),
    ]
