# Generated by Django 4.0 on 2021-12-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_credit_credit_debit_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='entryNumber',
            field=models.IntegerField(),
        ),
    ]
